### ISSUE TITLE
Users association with Locations

### ISSUE THREAD

**Issue by jacksonjunelee** [jjlee5266/DatabaseApp#1]
@harimohanraj89 
@DrRobotmck 
@htella 
This is a conceptual question. Currently, I have a signup page and I want at the time of the sign up for the user to be associated with a location. However, I don't know what is the best method to link them.

**Comment by jacksonjunelee** [comment]
My initial idea is to have them write the location, turn in to lowercase and find it in the database

**Comment by harimohanraj89** [comment]
That would be valid. You could also have a dropdown menu (or radio buttons) with all the locations in your database on the sign up page.

**Comment by jacksonjunelee** [comment]
I don't want them to see the locations

**Comment by harimohanraj89** [comment]
Then your initial idea would work fine.

**Comment by jacksonjunelee** [comment]
I am planning on having multiple headquarters(companies) in my database and when users sign up I do not want them to see the headquarters. 

I set up a jqeury.val() on the input box to get the company information but I need to fire an ajax request to retrieve the information however the authorization is preventing me from accessing the information until they sign up.

**Comment by harimohanraj89** [comment]
Paste relevant code sections here.

**Comment by jjlee5266** [comment]
#before this javascript code is just the setup for a form
# the javascript looks at input#user_company and on blur takes the value and sends an ajax request
#However the authorization is stopping the ajax request because he is not signed in
  
<script>$('#user_company').on('blur',function(){
    var company = $(this).val().toLowerCase();
    $.get('/locations').done(function(data){
      console.log(this);
      console.log(data);
      consoel.log("milk")
    })


    })</script>

**Comment by jjlee5266** [comment]
/code  
<script>$('#user_company').on('blur',function(){
    var company = $(this).val().toLowerCase();
    $.get('/locations').done(function(data){
      console.log(this);
      console.log(data);
      consoel.log("milk")
    })


    })</script>

**Comment by jacksonjunelee** [comment]
//before this script code is just the setup for a signup form
// script code looks at input#user_company and on blur takes the value and sends an ajax request
// the authorization is stopping the ajax request because he is not signed in

$('#user_company').on('blur',function(){
    var company = $(this).val().toLowerCase();
    $.get('/locations').done(function(data){
      console.log(this);
      console.log(data);
      consoel.log("milk")
    })
    })</script>

**Comment by harimohanraj89** [comment]
Is there a reason that you need to go fetch the location information before the user has finished signing up? Can you wait until the user submits all the sign up information?

**Comment by jacksonjunelee** [comment]
Yes but for user convenience I would like to have it set up that way
